# Generated by Django 4.2.6 on 2023-10-20 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket",
                    models.IntegerField(
                        db_index=True,
                        help_text="ID of the trade on the trading platform",
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("L", "Long"), ("S", "Short")], max_length=1
                    ),
                ),
                ("open_datetime", models.DateTimeField()),
                ("close_datetime", models.DateTimeField()),
                ("open_price", models.FloatField()),
                ("stop_loss", models.FloatField()),
                ("take_profit", models.FloatField()),
                ("close_price", models.FloatField()),
                ("volume", models.FloatField(default=0.01)),
                ("pnl", models.FloatField(help_text="Profit/loss in USD")),
                (
                    "currency_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.currencypair",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
