# Generated by Django 4.2.5 on 2023-09-10 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(help_text="ISO 4217 Currency Code", max_length=3),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="CurrencyPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(blank=True, max_length=64, null=True)),
                ("description", models.CharField(max_length=128)),
                (
                    "usd_per_lot",
                    models.FloatField(
                        default=10, help_text="Quantity of USD per standard lot"
                    ),
                ),
                (
                    "pnl_multiplier",
                    models.IntegerField(
                        default=10000,
                        help_text="Value used to calculate the total profit/loss in pips",
                    ),
                ),
                (
                    "swap_long",
                    models.FloatField(
                        help_text="In-points overnight interest for a long position"
                    ),
                ),
                (
                    "swap_short",
                    models.FloatField(
                        help_text="In-points overnight interest for a short position"
                    ),
                ),
                (
                    "base_currency",
                    models.ForeignKey(
                        help_text="Currency that is being bought or sold",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="base_currency",
                        to="assets.currency",
                    ),
                ),
                (
                    "quote_currency",
                    models.ForeignKey(
                        help_text="Currency that is used to price the base currency",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_currency",
                        to="assets.currency",
                    ),
                ),
            ],
        ),
    ]
