# Generated by Django 4.2.6 on 2023-10-20 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="ISO 4217 Currency Code", max_length=3, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="CurrencyPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=128)),
                (
                    "pip_decimal_position",
                    models.IntegerField(
                        default=4,
                        help_text="Decimal position use to calculate pip movement.",
                    ),
                ),
                (
                    "base_currency",
                    models.ForeignKey(
                        help_text="Currency that is being bought or sold",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="base_currency",
                        to="assets.currency",
                    ),
                ),
                (
                    "quote_currency",
                    models.ForeignKey(
                        help_text="Currency that is used to price the base currency",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_currency",
                        to="assets.currency",
                    ),
                ),
            ],
        ),
    ]
