# Generated by Django 4.2.7 on 2023-12-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencypair",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
