# Generated by Django 4.2.5 on 2023-09-11 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_alter_currencypair_swap_long_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="currencypair",
            old_name="description",
            new_name="name",
        ),
    ]
