# Generated by Django 4.2.5 on 2023-09-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0003_rename_description_currencypair_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currencypair",
            name="pnl_multiplier",
        ),
        migrations.RemoveField(
            model_name="currencypair",
            name="usd_per_lot",
        ),
        migrations.AddField(
            model_name="currencypair",
            name="contract_size",
            field=models.FloatField(default=100000),
        ),
        migrations.AddField(
            model_name="currencypair",
            name="usd_per_pip",
            field=models.FloatField(default=1, help_text="Profit/loss in USD per pip"),
        ),
    ]
