# Generated by Django 4.2.5 on 2023-09-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0004_remove_currencypair_pnl_multiplier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currencypair",
            name="usd_per_pip",
        ),
        migrations.AddField(
            model_name="currencypair",
            name="pip_decimal_position",
            field=models.IntegerField(
                default=4, help_text="Decimal position use to calculate pip movement."
            ),
        ),
    ]
