# Generated by Django 4.2.7 on 2023-12-08 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(
                db_index=True, help_text="ISO 3166 code", max_length=2, unique=True
            ),
        ),
        migrations.CreateModel(
            name="EconomicIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=512)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="economic_indicators",
                        to="countries.country",
                    ),
                ),
            ],
            options={
                "unique_together": {("country", "name")},
            },
        ),
        migrations.CreateModel(
            name="EconomicReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=1024)),
                (
                    "impact_level",
                    models.IntegerField(choices=[(1, "Low"), (2, "Mid"), (3, "High")]),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        help_text="Publication datetime of the economic report"
                    ),
                ),
                ("unit", models.CharField(default="", max_length=8)),
                ("actual", models.FloatField(blank=True, null=True)),
                ("forecast", models.FloatField(blank=True, null=True)),
                ("previous", models.FloatField(blank=True, null=True)),
                (
                    "economic_indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="economic_reports",
                        to="countries.economicindicator",
                    ),
                ),
            ],
            options={
                "unique_together": {("economic_indicator", "datetime")},
            },
        ),
    ]
