# Generated by Django 4.2.4 on 2023-09-05 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "broker",
                    models.CharField(
                        help_text="Broker in which the account is registered",
                        max_length=128,
                    ),
                ),
                (
                    "equity",
                    models.FloatField(
                        default=0.0, help_text="Total equity of the trading account"
                    ),
                ),
                (
                    "total_deposited",
                    models.FloatField(
                        default=0.0,
                        help_text="Total amount of USD deposited into the trading account",
                    ),
                ),
                (
                    "total_withdrawn",
                    models.FloatField(
                        default=0.0,
                        help_text="Total amount of USD withdrawn from the trading account",
                    ),
                ),
                (
                    "total_lost",
                    models.FloatField(
                        default=0.0, help_text="Total amount of USD lost on trades"
                    ),
                ),
                (
                    "total_profited",
                    models.FloatField(
                        default=0.0, help_text="Total amount of USD profited on trades"
                    ),
                ),
                (
                    "added_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Datetime at which the account was added to this platform",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("DP", "deposit"), ("WT", "withdrawal")], max_length=2
                    ),
                ),
                ("amount", models.FloatField()),
                ("date", models.DateField(auto_now_add=True)),
                ("time", models.TimeField(auto_now_add=True)),
                (
                    "trading_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.tradingaccount",
                    ),
                ),
            ],
        ),
    ]
