# Generated by Django 4.2.5 on 2023-09-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_tradingaccount_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingaccount",
            name="type",
            field=models.CharField(
                choices=[("DM", "demo"), ("RL", "real")],
                default="DM",
                help_text="Trading accounts can be either DEMO or REAL",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="concept",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
