# Generated by Django 4.2.5 on 2023-09-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_tradingaccount_type_transaction_concept"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="public",
            field=models.BooleanField(
                default=True,
                help_text="If True, the profile will be retriverable by other users",
            ),
        ),
    ]
