# Generated by Django 4.2.5 on 2023-09-09 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_public"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="public",
            new_name="is_public",
        ),
    ]
