# Generated by Django 4.2.5 on 2023-09-08 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_tradingaccount_type_transaction_concept"),
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operation",
            name="leverage",
        ),
        migrations.AddField(
            model_name="operation",
            name="trading_account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.tradingaccount",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="operation",
            name="position",
            field=models.CharField(
                choices=[("LN", "long"), ("SH", "short")], max_length=2
            ),
        ),
    ]
