# Generated by Django 4.2.5 on 2023-09-22 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(help_text="ISO 4217 Currency Code", max_length=3),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="CurrencyPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(blank=True, max_length=64, null=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "pip_decimal_position",
                    models.IntegerField(
                        default=4,
                        help_text="Decimal position use to calculate pip movement.",
                    ),
                ),
                (
                    "base_currency",
                    models.ForeignKey(
                        help_text="Currency that is being bought or sold",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="base_currency",
                        to="forex.currency",
                    ),
                ),
                (
                    "quote_currency",
                    models.ForeignKey(
                        help_text="Currency that is used to price the base currency",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_currency",
                        to="forex.currency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ForexOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("L", "Long"), ("S", "Short")], max_length=1
                    ),
                ),
                ("opened_on", models.DateTimeField(auto_now_add=True)),
                ("closed_on", models.DateTimeField(auto_now_add=True)),
                ("open_price", models.FloatField()),
                ("close_price", models.FloatField()),
                ("volume", models.FloatField(default=0.01)),
                ("pnl", models.FloatField(help_text="Profit/loss in USD")),
                (
                    "currency_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="forex.currencypair",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
