# Generated by Django 4.2.6 on 2023-10-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forex", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="symbol",
            field=models.CharField(
                help_text="ISO 4217 Currency Code", max_length=3, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="currencypair",
            name="name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="currencypair",
            name="symbol",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="forexoperation",
            name="ticket",
            field=models.IntegerField(
                db_index=True,
                help_text="ID of the trade on the trading platform",
                unique=True,
            ),
        ),
    ]
